services:
  vehiclefeecalculator:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.dev
    ports:
      - "${APP_PORT:-443}:443"
    volumes:
      - .:/app
      - ./infrastructure/ssl:/etc/ssl/frankenphp
    environment:
      - APP_ENV=dev
      - HTTPS=true
      - SERVER_NAME=:443
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 