FROM dunglas/frankenphp

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    nodejs \
    npm

# Install PHP extensions
RUN install-php-extensions \
    pdo_mysql \
    zip \
    xdebug

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy project files
COPY . .

# Install dependencies
RUN composer install
RUN npm install

EXPOSE 80
EXPOSE 443
EXPOSE 5173

CMD ["frankenphp", "run", "--config", "/app/frankenphp/Caddyfile"] 