FROM dunglas/frankenphp

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    nodejs \
    npm

# Install PHP extensions
RUN install-php-extensions \
    pdo_mysql \
    zip \
    xdebug

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy project files
COPY . .

EXPOSE 443

CMD ["frankenphp", "run", "--config", "/app/infrastructure/frankenphp/Caddyfile"] 